from typing import Any, Optional

def as_rows(string: Any): ...
def csv_clean_header(header_row: Any): ...
def csv_dict_reader(fileobj: Any, **kw: Any): ...
def csv_tuple_reader(fileobj: Any, **kw: Any) -> None: ...
def csv_split_sections(rows: Any): ...
def csv_split_sections_with_titles(rows: Any): ...
def iter_sections(fileobj: Any, separating_predicate: Optional[Any] = ...): ...
def iter_until_empty(iterator: Any, separating_predicate: Optional[Any] = ...): ...
