import unittest
from beancount.utils import csv_utils as csv_utils, test_utils as test_utils
from typing import Any

class TestCSVUtils(unittest.TestCase):
    def test_csv_clean_header(self) -> None: ...
    def test_csv_dict_reader(self, filename: Any) -> None: ...
    def test_csv_tuple_reader(self, filename: Any) -> None: ...
    def test_csv_split_sections(self) -> None: ...
    def test_csv_split_sections_with_titles(self) -> None: ...

def linearize(iterator: Any, joiner: Any = ...): ...

class TestLineUtils(unittest.TestCase):
    def test_iter_until_empty(self) -> None: ...
    def test_iter_section(self) -> None: ...
