from typing import Any, Optional

def iter_dates(start_date: Any, end_date: Any) -> None: ...
def parse_date_liberally(string: Any, parse_kwargs_dict: Optional[Any] = ...): ...
def render_ofx_date(dtime: Any): ...
def next_month(date: Any): ...
def intimezone(tz_value: str) -> Any: ...
