import unittest
from beancount.utils import date_utils as date_utils

class TestDateUtils(unittest.TestCase):
    def test_iter_dates(self) -> None: ...
    def test_parse_date_liberally(self) -> None: ...
    def test_next_month(self) -> None: ...
    def test_intimezone(self) -> None: ...
