import collections
from typing import Any, Optional

class DefaultDictWithKey(collections.defaultdict):
    def __missing__(self, key: Any): ...

NOTFOUND: Any

class ImmutableDictWithDefault(dict):
    default: Any = ...
    def __init__(self, *args: Any, default: Optional[Any] = ...) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def get(self, key: Any, _: Optional[Any] = ...): ...
    def __reduce__(self): ...
