import unittest
from beancount.utils import encryption as encryption, test_utils as test_utils
from typing import Any

TEST_PUBLIC_KEY: str
TEST_SECRET_KEY: str
INPUT: str

class TestEncryptedBase(unittest.TestCase):
    tmpdir: Any = ...
    ringdir: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def run_gpg(self, *args: Any, **kw: Any): ...
    def encrypt_as_file(self, string: Any, encrypted_filename: Any) -> None: ...

class TestEncryptedFiles(TestEncryptedBase):
    def test_read_encrypted_file(self) -> None: ...

class TestEncryptedFilesCheck(unittest.TestCase):
    def test_is_encrypted_file(self) -> None: ...
