import unittest
from beancount.utils import file_type as file_type
from typing import Any

class TestFileType(unittest.TestCase):
    DATA_DIR: Any = ...
    def check_mime_type(self, example_file: Any, expected_mime_types: Any) -> None: ...
    def test_csv(self) -> None: ...
    def test_xls(self) -> None: ...
    def test_ods(self) -> None: ...
    def test_ps(self) -> None: ...
    def test_pdf(self) -> None: ...
    def test_ofx(self) -> None: ...
    def test_qbo(self) -> None: ...
    def test_qfx(self) -> None: ...
    def test_py(self) -> None: ...
    def test_sh(self) -> None: ...
    def test_jpg(self) -> None: ...
    def test_txt(self) -> None: ...
    def test_org(self) -> None: ...
    def test_xml(self) -> None: ...
    def test_html(self) -> None: ...
    def test_xhtml(self) -> None: ...
    def test_zip(self) -> None: ...
    def test_gz(self) -> None: ...
    def test_bz2(self) -> None: ...
