from typing import Any, Optional

def find_files(fords: Any, ignore_dirs: Any = ..., ignore_files: Any = ...) -> None: ...
def guess_file_format(filename: Any, default: Optional[Any] = ...): ...
def path_greedy_split(filename: Any): ...
def touch_file(filename: Any, *otherfiles: Any) -> None: ...
def chdir(directory: Any) -> None: ...
