import unittest
from beancount.utils import file_utils as file_utils, test_utils as test_utils
from typing import Any

def clean(prefix: Any, iterable: Any): ...

class TestFileUtilsFind(test_utils.TestTempdirMixin, test_utils.TestCase):
    def setUp(self) -> None: ...
    def test_find_files(self): ...

class TestMiscFileUtils(unittest.TestCase):
    def test_guess_file_format(self) -> None: ...
    def test_path_greedy_split(self) -> None: ...
    def test_chdir_contextmanager(self) -> None: ...
