import unittest
from beancount.utils import invariants as invariants

class Dummy:
    counter: int = ...
    def do_something(self) -> None: ...

class TestInvariants(unittest.TestCase):
    def setUp(self): ...
    def tearDown(self) -> None: ...
    def test_invariants_on_dummy(self) -> None: ...
