from typing import Any

def invariant_check(method: Any, prefun: Any, postfun: Any): ...
def instrument_invariants(klass: Any, prefun: Any, postfun: Any) -> None: ...
def uninstrument_invariants(klass: Any) -> None: ...
