import unittest
from beancount.utils import misc_utils as misc_utils, test_utils as test_utils
from typing import Any

def raise_import_error(*args: Any, **kw: Any) -> None: ...

class TestMiscUtils(unittest.TestCase):
    def test_deprecated(self, warn: Any) -> None: ...
    def test_log_time(self) -> None: ...
    def test_box(self) -> None: ...
    def test_swallow(self) -> None: ...
    def test_groupby(self): ...
    def test_filter_type(self) -> None: ...
    def test_longest(self) -> None: ...
    def test_skipiter(self) -> None: ...
    def test_get_tuple_values(self): ...
    def test_replace_tuple_values(self): ...
    def test_compute_unique_clean_ids(self) -> None: ...
    def test_idify(self) -> None: ...
    def test_map_namedtuple_attributes(self): ...
    def test_staticvar(self): ...
    def test_first_paragraph(self) -> None: ...
    def test_get_screen_width(self) -> None: ...
    def test_no_curses(self) -> None: ...
    def test_get_screen_height(self) -> None: ...
    def test_cmptuple(self) -> None: ...
    def test_is_sorted(self) -> None: ...
    def test_escape_string(self) -> None: ...

class TestUniquify(unittest.TestCase):
    def test_sorted_uniquify_first(self): ...
    def test_sorted_uniquify_last(self): ...
    def test_uniquify_first(self): ...
    def test_uniquify_last(self): ...

class TestLineFileProxy(unittest.TestCase):
    def test_line_file_proxy(self) -> None: ...
