import unittest
from beancount.utils import net_utils as net_utils

class TestRetryingUrlopen(unittest.TestCase):
    def test_success_200(self) -> None: ...
    def test_success_other(self) -> None: ...
    def test_timeout_once(self) -> None: ...
    def test_max_retry(self) -> None: ...
