import unittest
from beancount.utils import pager as pager, test_utils as test_utils

class TestPager(unittest.TestCase):
    def test_pager_nothreshold(self) -> None: ...
    def test_pager_threshold_below(self) -> None: ...
    def test_pager_threshold_above(self) -> None: ...
