from typing import Any, Optional

DEFAULT_PAGER: str

def create_pager(command: Any, file: Any): ...

class ConditionalPager:
    command: Any = ...
    minlines: Any = ...
    default_file: Any = ...
    def __init__(self, command: Any, minlines: Optional[Any] = ...) -> None: ...
    file: Any = ...
    pipe: Any = ...
    accumulated_data: Any = ...
    accumulated_lines: int = ...
    def __enter__(self): ...
    def flush_accumulated(self, file: Any) -> None: ...
    def write(self, data: Any) -> None: ...
    def __exit__(self, type: Any, value: Any, unused_traceback: Any): ...

def flush_only(fileobj: Any) -> None: ...
