from typing import Any, Optional

def iterlinks(html: Any, html_path: Any) -> None: ...
def scrape_urls(url_format: Any, callback: Any, ignore_regexp: Optional[Any] = ...): ...
def validate_local_links(filename: Any): ...
def validate_local_links_in_dir(directory: Any): ...
