import threading
from typing import Any, Optional

class Snoop:
    value: Any = ...
    history: Any = ...
    def __init__(self, maxlen: Optional[Any] = ...) -> None: ...
    def __call__(self, value: Any): ...
    def __getattr__(self, attr: Any): ...

snooper: Any

def snoopify(function: Any): ...

class _Saver(threading.local):
    value: Any = ...
    def __call__(self, value: Any): ...

save: Any
