import unittest
from beancount.utils import snoop as snoop

class TestSnoop(unittest.TestCase):
    def test_snoop(self) -> None: ...
    def test_snoop_regexp(self) -> None: ...
    def test_snoop_attribute(self) -> None: ...
    def test_snoopify(self) -> None: ...

class TestSaver(unittest.TestCase):
    def test_saver(self) -> None: ...
