import unittest
from beancount.utils import table as table

class TestTable(unittest.TestCase):
    def test_attribute_to_title(self) -> None: ...
    def test_create_table(self): ...
    def test_create_table_with_index(self) -> None: ...
    def test_table_to_html(self) -> None: ...
    def test_table_to_text(self) -> None: ...
    def test_table_to_csv(self) -> None: ...
    def test_compute_table_widths(self) -> None: ...
    def test_generate_table(self) -> None: ...
