from collections import namedtuple
from typing import Any, Optional

Table = namedtuple('Table', 'columns header body')

def attribute_to_title(fieldname: Any): ...
def create_table(rows: Any, field_spec: Optional[Any] = ...): ...
def table_to_html(table: Any, classes: Optional[Any] = ..., file: Optional[Any] = ...): ...
def table_to_text(table: Any, column_interspace: str = ..., formats: Optional[Any] = ...): ...
def table_to_csv(table: Any, file: Optional[Any] = ..., **kwargs: Any): ...
def compute_table_widths(rows: Any): ...
def render_table(table_: Any, output: Any, output_format: Any, css_id: Optional[Any] = ..., css_class: Optional[Any] = ...) -> None: ...
