[build-system]
requires = ['setuptools', 'uv']
build-backend = 'setuptools.build_meta'

[project]
name = 'beanprice'
version = '2.1.0'
description = 'Price quotes fetcher for Beancount'
license = { file = 'COPYING' }
readme = 'README.md'
authors = [
    { name = 'Martin Blais', email = 'blais@furius.ca' },
]
maintainers = [
    { name = 'Martin Blais', email = 'blais@furius.ca' },
]
keywords = [
    'accounting', 'ledger', 'beancount', 'price'
]
classifiers = [
    'License :: OSI Approved :: GNU General Public License v2 (GPLv2)',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: SQL',
    'Topic :: Office/Business :: Financial :: Accounting',
]
requires-python = '>= 3.9'
dependencies = [
    'beancount >= 3.0.0',
    'python-dateutil >= 2.6.0',
    'requests >= 2.0',
    'curl_cffi>=0.6.5',
    "diskcache>=5.6.3",
]

[project.scripts]
bean-price = 'beanprice.price:main'

[project.urls]
homepage = 'https://github.com/beancount/beanprice'
issues = 'https://github.com/beancount/beanprice/issues'

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pylint==3.3.3",
    "mypy==1.14.1",
    "ruff>=0.9.0"
]

[tool.setuptools.packages]
find = {}

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = [
    'if typing.TYPE_CHECKING:',
]

# pylint and ruff are not aligned on this... maybe removing pylint would solve the problem.
ignore = [
    'C0301',
]

[tool.mypy]
disable_error_code = ["import-untyped"]
