from beancount.scripts import bake as bake
from beancount.utils import file_utils as file_utils, test_utils as test_utils
from typing import Any

class TestBakeFunctions(test_utils.TestCase):
    def check(self, from_: Any, to_: Any) -> None: ...
    def test_normalize_directories(self) -> None: ...
    def test_normalize_normal(self) -> None: ...
    def test_normalize_untouched(self) -> None: ...
    def test_normalize_other(self) -> None: ...
    def test_normalize_protected(self) -> None: ...
    test_html: Any = ...
    expected_html: Any = ...
    maxDiff: Any = ...
    def test_relativize_links(self) -> None: ...
    nolinks_html: Any = ...
    def test_remove_links(self) -> None: ...
    def test_save_scraped_document__file(self) -> None: ...
    def test_save_scraped_document__ignore_directories(self) -> None: ...
    def test_save_scraped_document__binary_content(self) -> None: ...

class TestScriptBake(test_utils.TestCase):
    def get_args(self): ...
    def test_bake_missing_input(self) -> None: ...
    def test_bake_output_collision(self, filename: Any) -> None: ...
    def test_bake_directory(self, filename: Any) -> None: ...

class TestScriptArchive(TestScriptBake):
    def test_bake_archive__known(self, filename: Any) -> None: ...
    def test_bake_archive__unknown(self, filename: Any) -> None: ...
