from beancount.parser import version as version
from beancount.utils import file_utils as file_utils, scrape as scrape
from beancount.web import web as web
from typing import Any

BINARY_DIRECTORIES: Any
BINARY_MATCH: Any

def normalize_filename(url: Any): ...
def relativize_links(html: Any, current_url: Any) -> None: ...
def remove_links(html: Any, targets: Any) -> None: ...
def save_scraped_document(output_dir: Any, url: Any, response: Any, contents: Any, html_root: Any, skipped_urls: Any) -> None: ...
def bake_to_directory(webargs: Any, output_dir: Any, render_all_pages: bool = ...) -> None: ...
def archive(command_template: Any, directory: Any, archive: Any, quiet: bool = ...) -> None: ...
def archive_zip(directory: Any, archive: Any) -> None: ...

ARCHIVERS: Any

def main() -> None: ...
