from typing import Any, Optional

def list_dependencies(file: Any = ...) -> None: ...
def check_dependencies(): ...
def check_python(): ...
def is_fast_decimal(decimal_module: Any): ...
def check_cdecimal(): ...
def check_python_magic(): ...
def check_import(package_name: Any, min_version: Optional[Any] = ..., module_name: Optional[Any] = ...): ...
def parse_version(version_str: str) -> str: ...
