import unittest
from beancount.scripts import directories as directories
from typing import Any

class TestScriptCheckDirectories(unittest.TestCase):
    tmpdir: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    TEST_DIRECTORIES: Any = ...
    def test_validation(self) -> None: ...
    def test_validation_no_parent(self) -> None: ...
