from beancount.core import account as account, amount as amount
from beancount.parser import version as version
from typing import Any, Optional

def align_beancount(contents: Any, prefix_width: Optional[Any] = ..., num_width: Optional[Any] = ..., currency_column: Optional[Any] = ...): ...
def compute_most_frequent(iterable: Any): ...
def normalize_indent_whitespace(match_pairs: Any): ...
def main(): ...
