from beancount.utils import test_utils as test_utils
from typing import Any, Optional

def is_bazel_build(): ...

class TestSetup(test_utils.TestCase):
    installdir: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_setup(self) -> None: ...
    def run_setup(self, installdir: Any, extra_env: Optional[Any] = ...) -> None: ...
    def test_sdist_includes_c_files(self) -> None: ...
