SOURCE_HASH: str

class Parser:
    def __init__(self, *args, **kwargs) -> None: ...
    def lex(file, filename = ..., lineno = ..., encoding = ...) -> Any: ...
    def parse(file, filename = ..., lineno = ..., encoding = ...) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
