from beancount.core import convert as convert, flags as flags, inventory as inventory, position as position
from beancount.core.amount import Amount as Amount
from beancount.core.data import Booking as Booking
from beancount.core.number import ZERO as ZERO
from beancount.core.position import Cost as Cost
from collections import namedtuple
from typing import Any

AmbiguousMatchError = namedtuple('AmbiguousMatchError', 'source message entry')

def handle_ambiguous_matches(entry: Any, posting: Any, matches: Any, method: Any): ...
def booking_method_STRICT(entry: Any, posting: Any, matches: Any): ...
def booking_method_FIFO(entry: Any, posting: Any, matches: Any): ...
def booking_method_LIFO(entry: Any, posting: Any, matches: Any): ...
def booking_method_NONE(entry: Any, posting: Any, matches: Any): ...
def booking_method_AVERAGE(entry: Any, posting: Any, matches: Any): ...
