from beancount.core import amount as amount, data as data, inventory as inventory, position as position
from beancount.core.number import MISSING as MISSING, ZERO as ZERO
from beancount.parser import booking_full as booking_full
from collections import namedtuple
from typing import Any

BookingError = namedtuple('BookingError', 'source message entry')

def book(incomplete_entries: Any, options_map: Any): ...
def validate_missing_eliminated(entries: Any, unused_options_map: Any): ...
def validate_inventory_booking(entries: Any, unused_options_map: Any, booking_methods: Any): ...
def convert_lot_specs_to_lots(entries: Any): ...
def convert_spec_to_cost(units: Any, cost_spec: Any): ...
