import unittest
from beancount.core import amount as amount, compare as compare, data as data, position as position
from beancount.core.number import MISSING as MISSING, ZERO as ZERO
from beancount.parser import booking as booking, parser as parser, printer as printer
from beancount.utils import test_utils as test_utils
from typing import Any

class TestError(Exception): ...

def read_string_or_entries(entries_or_str: Any, allow_incomplete: bool = ...): ...

class TestCase(unittest.TestCase):
    def assertEqualEntries(self, expected_entries: Any, actual_entries: Any): ...
    def assertIncludesEntries(self, subset_entries: Any, entries: Any): ...
    def assertExcludesEntries(self, subset_entries: Any, entries: Any): ...

DEFAULT_FAILFUNC: Any

def assertEqualEntries(expected_entries: Any, actual_entries: Any, failfunc: Any = ..., allow_incomplete: bool = ...) -> None: ...
def assertIncludesEntries(subset_entries: Any, entries: Any, failfunc: Any = ..., allow_incomplete: bool = ...) -> None: ...
def assertExcludesEntries(subset_entries: Any, entries: Any, failfunc: Any = ..., allow_incomplete: bool = ...) -> None: ...
