import unittest
from beancount.core import amount as amount, data as data, position as position
from beancount.core.number import MISSING as MISSING
from beancount.parser import booking as booking, cmptest as cmptest, parser as parser
from typing import Any

class TestCompareTestFunctions(unittest.TestCase):
    def test_read_string_or_entries(self) -> None: ...
    def test_local_booking(self) -> None: ...

class TestTestCase(cmptest.TestCase):
    ledger_text: Any = ...
    def setUp(self) -> None: ...
    def test_assertEqualEntries(self) -> None: ...
    def test_assertIncludesEntries(self) -> None: ...
    def test_assertExcludesEntries(self) -> None: ...
