import types
from typing import Any

PARSER_SOURCE_FILES: Any

def hash_parser_source_files(): ...
def check_parser_source_files(parser_module: types.ModuleType) -> Any: ...
def gen_include(): ...
def main() -> None: ...
