from beancount.core.data import new_metadata as new_metadata
from collections import namedtuple
from typing import Any, Optional

LexerError = namedtuple('LexerError', 'source message entry')

class LexBuilder:
    errors: Any = ...
    def __init__(self) -> None: ...
    def build_lexer_error(self, filename: Any, lineno: Any, message: Any) -> None: ...

def lex_iter(file: Any, builder: Optional[Any] = ..., encoding: Optional[Any] = ...) -> None: ...
def lex_iter_string(string: Any, builder: Optional[Any] = ..., **kwargs: Any) -> None: ...
