from beancount.core import account as account, account_types as account_types, data as data, display_context as display_context
from beancount.core.number import D as D
from collections import namedtuple
from typing import Any, Optional

def options_validate_processing_mode(value: Any): ...
def options_validate_plugin(value: Any): ...
def options_validate_tolerance(value: Any): ...
def options_validate_tolerance_map(value: Any): ...
def options_validate_boolean(value: Any): ...
def options_validate_booking_method(value: Any): ...

OptGroup = namedtuple('OptGroup', 'description options')

OptDesc = namedtuple('OptDesc', 'name default_value example_value converter deprecated alias')
UNSET: Any

def Opt(name: Any, default_value: Any, example_value: Any = ..., converter: Optional[Any] = ..., deprecated: bool = ..., alias: Optional[Any] = ...): ...

OUTPUT_OPTION_GROUPS: Any
PUBLIC_OPTION_GROUPS: Any
OPTION_GROUPS: Any
OPTIONS: Any
OPTIONS_DEFAULTS: Any
READ_ONLY_OPTIONS: Any

def get_account_types(options: Any): ...
def get_previous_accounts(options: Any): ...
def get_current_accounts(options: Any): ...
def list_options(): ...
