import unittest
from beancount.core import account_types as account_types
from beancount.parser import options as options, parser as parser
from typing import Any

class TestOptions(unittest.TestCase):
    def test_get_account_types(self) -> None: ...
    def test_get_previous_accounts(self) -> None: ...
    def test_get_current_accounts(self) -> None: ...
    def test_list_options(self) -> None: ...

class TestAccountTypeOptions(unittest.TestCase):
    def test_custom_account_names__success(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_custom_account_names__success_reset(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_custom_account_names__basic_fail(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_custom_account_names__fail_invalid_order(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_custom_account_names__fail_invalid_other(self, entries: Any, errors: Any, options_map: Any) -> None: ...

class TestValidateOptions(unittest.TestCase):
    def test_validate__plugin_processing_mode__invalid(self, entries: Any, errors: Any, options_map: Any) -> None: ...
