from beancount.core import data as data
from beancount.core.number import MISSING as MISSING
from beancount.parser import grammar as grammar, hashsrc as hashsrc, printer as printer
from beancount.parser.grammar import DeprecatedError as DeprecatedError, ParserError as ParserError, ParserSyntaxError as ParserSyntaxError
from typing import Any, Optional

def is_posting_incomplete(posting: Any): ...
def is_entry_incomplete(entry: Any): ...
def parse_file(file: Any, report_filename: Optional[Any] = ..., report_firstline: int = ..., **kw: Any): ...
def parse_string(string: Any, report_filename: Optional[Any] = ..., **kw: Any): ...
def parse_doc(expect_errors: bool = ..., allow_incomplete: bool = ...): ...
def parse_many(string: Any, level: int = ...): ...
def parse_one(string: Any): ...
