import unittest
from beancount.parser import version as version
from beancount.utils import test_utils as test_utils

class TestVersion(unittest.TestCase):
    def test_version_exists(self) -> None: ...
    def test_compute_version_string(self) -> None: ...
    def test_version(self) -> None: ...
