import unittest
from beancount.core import account_types as account_types
from typing import Any

class TestAccountTypes(unittest.TestCase):
    def test_basics(self) -> None: ...
    def test_get_account_sort_key(self) -> None: ...
    def test_get_account_type(self) -> None: ...
    def test_is_account_type(self) -> None: ...
    def test_is_root_account(self) -> None: ...
    OPTIONS: Any = ...
    def test_is_account_categories(self) -> None: ...
    def test_get_account_sign(self) -> None: ...
