import unittest
from beancount.core import account as account
from beancount.utils import test_utils as test_utils
from typing import Any

class TestAccount(unittest.TestCase):
    def test_is_valid(self) -> None: ...
    def test_account_join(self) -> None: ...
    def test_account_split(self) -> None: ...
    def test_parent(self) -> None: ...
    def test_leaf(self) -> None: ...
    def test_sans_root(self) -> None: ...
    def test_root(self) -> None: ...
    def test_has_component(self) -> None: ...
    def test_commonprefix(self) -> None: ...
    def test_parent_matcher(self) -> None: ...
    def test_parents(self) -> None: ...

class TestWalk(test_utils.TmpFilesTestBase):
    TEST_DOCUMENTS: Any = ...
    def test_walk(self) -> None: ...

class TestAccountTransformer(unittest.TestCase):
    def test_render(self) -> None: ...
    def test_parse(self) -> None: ...
    def test_noop(self) -> None: ...
