from beancount.core.display_context import DEFAULT_FORMATTER as DEFAULT_FORMATTER
from beancount.core.number import D as D, ZERO as ZERO
from typing import Any

CURRENCY_RE: str

class Amount(_Amount):
    valid_types_number: Any = ...
    valid_types_currency: Any = ...
    def __new__(cls, number: Any, currency: Any): ...
    def to_string(self, dformat: Any = ...): ...
    def __bool__(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    def __neg__(self): ...
    @staticmethod
    def from_string(string: Any): ...

def sortkey(amount: Any): ...
def mul(amount: Any, number: Any): ...
def div(amount: Any, number: Any): ...
def add(amount1: Any, amount2: Any): ...
def sub(amount1: Any, amount2: Any): ...
def abs(amount: Any): ...

A: Any

from_string: Any
NULL_AMOUNT: Any
