import unittest
from beancount import loader as loader
from beancount.core import compare as compare, data as data

TEST_INPUT: str

class TestCompare(unittest.TestCase):
    def test_hash_entries(self) -> None: ...
    def test_hash_entries_with_duplicates(self) -> None: ...
    def test_hash_entries_same_postings(self) -> None: ...
    def test_compare_entries(self) -> None: ...
    def test_includes_entries(self) -> None: ...
    def test_excludes_entries(self) -> None: ...
    def test_hash_with_exclude_meta(self) -> None: ...
