from beancount.core import data as data
from beancount.core.data import Price as Price
from collections import namedtuple
from typing import Any

CompareError = namedtuple('CompareError', 'source message entry')
IGNORED_FIELD_NAMES: Any

def stable_hash_namedtuple(objtuple: Any, ignore: Any = ...): ...
def hash_entry(entry: Any, exclude_meta: bool = ...): ...
def hash_entries(entries: Any, exclude_meta: bool = ...): ...
def compare_entries(entries1: Any, entries2: Any): ...
def includes_entries(subset_entries: Any, entries: Any): ...
def excludes_entries(subset_entries: Any, entries: Any): ...
