from beancount.core import prices as prices
from beancount.core.amount import Amount as Amount
from beancount.core.number import MISSING as MISSING
from beancount.core.position import Cost as Cost, Position as Position
from typing import Any, Optional

def get_units(pos: Any): ...
def get_cost(pos: Any): ...
def get_weight(pos: Any): ...
def get_value(pos: Any, price_map: Any, date: Optional[Any] = ..., output_date_prices: Optional[Any] = ...): ...
def convert_position(pos: Any, target_currency: Any, price_map: Any, date: Optional[Any] = ...): ...
def convert_amount(amt: Any, target_currency: Any, price_map: Any, date: Optional[Any] = ..., via: Optional[Any] = ...): ...
