import unittest
from beancount.core import data as data
from beancount.core.amount import A as A
from typing import Any

META: Any
FLAG: str

class TestData(unittest.TestCase):
    def create_empty_transaction(self): ...
    def test_create_simple_posting(self) -> None: ...
    def test_create_simple_posting_with_cost(self) -> None: ...
    def test_sanity_check_types(self) -> None: ...
    def test_posting_has_conversion(self) -> None: ...
    def test_transaction_has_conversion(self) -> None: ...
    def test_get_entry(self) -> None: ...
    def create_sort_data(self): ...
    def check_sorted(self, entries: Any) -> None: ...
    def test_entry_sortkey(self) -> None: ...
    def test_sort(self) -> None: ...
    def test_posting_sortkey(self) -> None: ...
    def test_filter_txns(self) -> None: ...
    def test_has_entry_account_component(self) -> None: ...
    def test_find_closest(self) -> None: ...
    def test_remove_account_postings(self) -> None: ...
    def test_iter_entry_dates(self) -> None: ...

class TestPickle(unittest.TestCase):
    def test_data_tuples_support_pickle(self) -> None: ...
