import unittest
from beancount import loader as loader
from beancount.core import data as data, getters as getters
from typing import Any

TEST_INPUT: str

class TestGetters(unittest.TestCase):
    def test_methods_coverage(self) -> None: ...
    def test_get_accounts_use_map(self) -> None: ...
    def test_get_accounts(self) -> None: ...
    def test_get_entry_accounts(self) -> None: ...
    def test_get_all_tags(self) -> None: ...
    def test_get_all_payees(self) -> None: ...
    def test_get_all_links(self) -> None: ...
    def test_get_leveln_parent_accounts(self) -> None: ...
    def test_get_dict_accounts(self) -> None: ...
    def test_get_min_max_dates(self) -> None: ...
    def test_get_active_years(self) -> None: ...
    def test_get_account_open_close(self): ...
    def test_get_account_open_close__duplicates(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_get_account_components(self) -> None: ...
    def test_get_commodity_directives(self) -> None: ...
    def test_get_values_meta__single(self) -> None: ...
    def test_get_values_meta__multi(self) -> None: ...
