import unittest
from beancount.core.number import D as D, ZERO as ZERO, round_to as round_to, same_sign as same_sign

class TestDecimalPrecision(unittest.TestCase):
    def test_formatting(self) -> None: ...

class TestToDecimal(unittest.TestCase):
    def test_ZERO(self) -> None: ...
    def test_D(self) -> None: ...
    def test_round_to(self) -> None: ...
    def test_same_sign(self) -> None: ...
