from beancount.core import data as data
from beancount.core.data import Currency as Currency, Price as Price
from beancount.core.number import ONE as ONE, ZERO as ZERO
from beancount.utils import bisect_key as bisect_key, misc_utils as misc_utils
from typing import Any, Optional, Set

def get_last_price_entries(entries: Any, date: Any): ...

class PriceMap(dict): ...

def build_price_map(entries: Any): ...
def project(orig_price_map: PriceMap, from_currency: Currency, to_currency: Currency, base_currencies: Optional[Set[Currency]]=...) -> PriceMap: ...
def normalize_base_quote(base_quote: Any): ...
def get_all_prices(price_map: Any, base_quote: Any): ...
def get_latest_price(price_map: Any, base_quote: Any): ...
def get_price(price_map: Any, base_quote: Any, date: Optional[Any] = ...): ...
