import unittest
from beancount import loader as loader
from beancount.core import prices as prices
from beancount.core.number import D as D
from beancount.parser import cmptest as cmptest
from typing import Any

class TestPriceEntries(cmptest.TestCase):
    def test_get_last_price_entries(self, entries: Any, _: Any, __: Any) -> None: ...

class TestPriceMap(unittest.TestCase):
    def test_normalize_base_quote(self) -> None: ...
    def test_build_price_map(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_build_price_map_zero_prices(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_lookup_price_and_inverse(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_get_all_prices(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_get_latest_price(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_get_price(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_ordering_same_date(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_project(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_project_missing(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_project_collisions(self, entries: Any, _: Any, __: Any) -> None: ...
