import unittest
from beancount.ingest import importer as importer
from beancount.ingest.importers import config as config
from typing import Any

class SimpleTestImporter(config.ConfigImporterMixin, importer.ImporterProtocol):
    REQUIRED_CONFIG: Any = ...

class TestConfigMixin(unittest.TestCase):
    default_config: Any = ...
    def setUp(self) -> None: ...
    def test_constructors(self) -> None: ...
    def test_file_account(self) -> None: ...
    def test_invalid_missing(self) -> None: ...
    def test_invalid_extra(self) -> None: ...
