import unittest
from beancount.core import data as data
from beancount.ingest import cache as cache
from beancount.ingest.importers import csv as csv
from beancount.parser import cmptest as cmptest
from beancount.utils import test_utils as test_utils
from typing import Any

Col: Any

class TestCSVFunctions(unittest.TestCase):
    def test_normalize_config__with_header(self) -> None: ...
    def test_normalize_config__with_skip_and_header(self) -> None: ...
    def test_normalize_config__without_header(self) -> None: ...
    def test_normalize_config__with_skip_and_without_header(self) -> None: ...

class TestCSVImporter(cmptest.TestCase):
    def test_column_types(self, filename: Any) -> None: ...
    def test_date_formats(self, filename: Any) -> None: ...
    def test_links(self, filename: Any) -> None: ...
    def test_tags(self, filename: Any) -> None: ...
    def test_zero_balance_produces_assertion(self, filename: Any) -> None: ...
    def test_categorizer_one_argument(self, filename: Any): ...
    def test_categorizer_two_arguments(self, filename: Any): ...
    def test_explict_encoding_utf8(self, filename: Any) -> None: ...
