from beancount.core.number import D as D
from beancount.ingest.importers import ofx as ofx
from beancount.parser import cmptest as cmptest, parser as parser
from typing import Any

def clean_xml(string: Any): ...

class TestOFXImporter(cmptest.TestCase):
    def test_parse_ofx_time(self) -> None: ...
    def test_find_acctids(self) -> None: ...
    def test_find_max_date(self) -> None: ...
    def test_find_currency(self) -> None: ...
    def test_find_statement_transactions(self) -> None: ...
    def test_find_child(self) -> None: ...
    def test_build_transaction(self) -> None: ...
    def test_extract_with_balance_declared(self) -> None: ...
    def test_extract_with_balance_last(self) -> None: ...
    def test_two_distinct_balances(self) -> None: ...
