import unittest
from beancount.ingest import cache as cache
from beancount.utils import file_type as file_type

class TestFileMemo(unittest.TestCase):
    def test_cache(self) -> None: ...
    def test_cache_head_and_contents(self) -> None: ...
    def test_cache_head_obeys_explict_utf8_encoding_avoids_chardet_exception(self) -> None: ...
