from beancount.utils import defdict as defdict, file_type as file_type
from typing import Any, Optional

HEAD_DETECT_MAX_BYTES: Any

class _FileMemo:
    name: Any = ...
    def __init__(self, filename: Any) -> None: ...
    def convert(self, converter_func: Any): ...
    def mimetype(self): ...
    def head(self, num_bytes: int = ..., encoding: Optional[Any] = ...): ...
    def contents(self): ...

def mimetype(filename: Any): ...
def head(num_bytes: int = ..., encoding: Optional[Any] = ...): ...
def contents(filename: Any): ...
def get_file(filename: Any): ...
