from beancount import loader as loader
from beancount.core import data as data
from beancount.ingest import cache as cache, identify as identify, similar as similar
from beancount.parser import printer as printer
from typing import Any, Optional

HEADER: str
DUPLICATE_META: str

def extract_from_file(filename: Any, importer: Any, existing_entries: Optional[Any] = ..., min_date: Optional[Any] = ..., allow_none_for_tags_and_links: bool = ...): ...
def find_duplicate_entries(new_entries_list: Any, existing_entries: Any): ...
def print_extracted_entries(entries: Any, file: Any): ...
def extract(importer_config: Any, files_or_directories: Any, output: Any, entries: Optional[Any] = ..., options_map: Optional[Any] = ..., mindate: Optional[Any] = ..., ascending: bool = ..., hooks: Optional[Any] = ...) -> None: ...

DESCRIPTION: str

def add_arguments(parser: Any) -> None: ...
def run(args: Any, _: Any, importers_list: Any, files_or_directories: Any, hooks: Optional[Any] = ...): ...
