from beancount.core import account as account
from beancount.ingest import cache as cache, identify as identify
from beancount.utils import misc_utils as misc_utils
from typing import Any, Optional

def file_one_file(filename: Any, importers: Any, destination: Any, idify: bool = ..., logfile: Optional[Any] = ...): ...
def file(importer_config: Any, files_or_directories: Any, destination: Any, dry_run: bool = ..., mkdirs: bool = ..., overwrite: bool = ..., idify: bool = ..., logfile: Optional[Any] = ...): ...
def move_xdev_file(src_filename: Any, dst_filename: Any, mkdirs: bool = ...) -> None: ...

DESCRIPTION: str

def add_arguments(parser: Any) -> None: ...
def run(args: Any, parser: Any, importers_list: Any, files_or_directories: Any, hooks: Optional[Any] = ...): ...
