import unittest
from beancount.ingest import identify as identify, scripts_utils as scripts_utils
from beancount.ingest.importer import ImporterProtocol as ImporterProtocol
from beancount.utils import test_utils as test_utils
from typing import Any

identify_main: Any

class _TestImporter(ImporterProtocol):
    filename: Any = ...
    def __init__(self, filename: Any) -> None: ...
    def identify(self, file: Any): ...

class TestScriptIdentifyFunctions(test_utils.TestTempdirMixin, unittest.TestCase):
    def test_find_imports(self) -> None: ...
    def test_find_imports__file_too_large(self) -> None: ...
    def test_find_imports__raises_exception(self) -> None: ...

class TestScriptIdentify(scripts_utils.TestScriptsBase):
    def test_identify(self) -> None: ...
    def test_identify_examples(self) -> None: ...
