from beancount.core import flags as flags
from typing import Any, Optional

class ImporterProtocol:
    FLAG: Any = ...
    def name(self): ...
    def identify(self, file: Any) -> None: ...
    def extract(self, file: Any, existing_entries: Optional[Any] = ...) -> None: ...
    def file_account(self, file: Any) -> None: ...
    def file_name(self, file: Any) -> None: ...
    def file_date(self, file: Any) -> None: ...
