import unittest
from beancount.ingest import importer as importer, regression as regression
from beancount.parser import parser as parser
from beancount.utils import test_utils as test_utils
from typing import Any

def suppress_deprecation(fun: Any): ...

class _DummyImporter(importer.ImporterProtocol): ...

class TestImporterTests(test_utils.TestTempdirMixin, unittest.TestCase):
    def test_test_expect_extract(self, extract_mock: Any) -> None: ...
    def test_test_expect_file_date(self) -> None: ...
    def test_test_expect_file_name(self) -> None: ...

class TestImporterTestGenerators(test_utils.TestTempdirMixin, unittest.TestCase):
    def test_find_input_files(self) -> None: ...
    def test_compare_sample_files__no_directory(self) -> None: ...
    def test_compare_sample_files__with_directory(self) -> None: ...
