import unittest
from beancount.ingest import cache as cache, extract as extract
from beancount.ingest.importer import ImporterProtocol as ImporterProtocol
from beancount.parser import printer as printer
from beancount.utils import test_utils as test_utils
from beancount.utils.misc_utils import deprecated as deprecated
from typing import Any, Optional

class ToolNotInstalled(OSError): ...

class ImportFileTestCase(unittest.TestCase):
    maxDiff: Any = ...
    importer: Any = ...
    def __init__(self, importer: Any) -> None: ...
    def test_expect_identify(self, filename: Any, msg: Any) -> None: ...
    def test_expect_extract(self, filename: Any, msg: Any) -> None: ...
    def test_expect_file_date(self, filename: Any, msg: Any) -> None: ...
    def test_expect_file_name(self, filename: Any, msg: Any) -> None: ...

def find_input_files(directory: Any) -> None: ...
def compare_sample_files(importer: Any, directory: Optional[Any] = ..., ignore_cls: Optional[Any] = ...) -> None: ...
