from beancount.ingest import cache as cache, extract as extract
from beancount.parser import printer as printer
from typing import Any

def pytest_addoption(parser: Any) -> None: ...
def with_importer(importer: Any): ...
def with_testdir(directory: Any): ...
def find_input_files(directory: Any) -> None: ...
def compare_contents_or_generate(actual_string: Any, expect_fn: Any, generate: Any) -> None: ...

class ImporterTestBase:
    def test_identify(self, importer: Any, file: Any) -> None: ...
    def test_extract(self, importer: Any, file: Any, pytestconfig: Any) -> None: ...
    def test_file_date(self, importer: Any, file: Any, pytestconfig: Any) -> None: ...
    def test_file_name(self, importer: Any, file: Any, pytestconfig: Any) -> None: ...
    def test_file_account(self, importer: Any, file: Any, pytestconfig: Any) -> None: ...
