from beancount import loader as loader
from beancount.core import data as data
from beancount.core.number import D as D
from beancount.ingest import similar as similar
from beancount.parser import cmptest as cmptest, parser as parser
from typing import Any

class TestDups(cmptest.TestCase):
    def test_find_similar_entries(self, entries: Any, _: Any, __: Any): ...
    def test_find_similar_entries__multiple_matches(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_amounts_map(self, entries: Any, _: Any, __: Any) -> None: ...

class TestSimilarityComparator(cmptest.TestCase):
    comparator: Any = ...
    def setUp(self) -> None: ...
    def test_simple(self, entries: Any, _: Any, __: Any) -> None: ...
