from beancount.core import amount as amount, data as data, interpolate as interpolate
from beancount.core.number import D as D, ONE as ONE, ZERO as ZERO
from typing import Any, Optional

def find_similar_entries(entries: Any, source_entries: Any, comparator: Optional[Any] = ..., window_days: int = ...): ...

class SimilarityComparator:
    EPSILON: Any = ...
    cache: Any = ...
    max_date_delta: Any = ...
    def __init__(self, max_date_delta: Optional[Any] = ...) -> None: ...
    def __call__(self, entry1: Any, entry2: Any): ...

def amounts_map(entry: Any): ...
