from beancount.core import data as data
from typing import Any

def filter_tag(tag: Any, entries: Any) -> None: ...
def filter_link(link: Any, entries: Any) -> None: ...
def group_entries_by_link(entries: Any): ...
def get_common_accounts(entries: Any): ...
