import unittest
from beancount import loader as loader
from beancount.core import data as data
from beancount.ops import basicops as basicops
from typing import Any

class TestBasicOpsLinks(unittest.TestCase):
    test_doc: Any = ...
    def test_filter_link(self) -> None: ...
    def test_group_entries_by_link(self) -> None: ...

class TestBasicOpsTags(unittest.TestCase):
    test_doc: Any = ...
    def test_filter_tag(self) -> None: ...

class TestBasicOpsOther(unittest.TestCase):
    def test_get_common_accounts(self, entries: Any, _: Any, __: Any) -> None: ...
