from beancount import loader as loader
from beancount.core import data as data
from beancount.ops import compress as compress
from beancount.parser import cmptest as cmptest
from typing import Any

class TestMerge(cmptest.TestCase):
    def test_merge(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_merge_cost(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_merge_price(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_unmergeable(self, entries: Any, errors: Any, __: Any) -> None: ...
