from beancount import loader as loader
from beancount.core import data as data
from beancount.ops import documents as documents
from beancount.parser import cmptest as cmptest
from beancount.utils import test_utils as test_utils
from typing import Any

class TestDocuments(test_utils.TmpFilesTestBase, cmptest.TestCase):
    TEST_DOCUMENTS: Any = ...
    def test_process_documents(self) -> None: ...
    def test_process_documents_trailing_slash(self) -> None: ...
    def test_verify_document_files_exist(self) -> None: ...
    def test_find_documents(self) -> None: ...

class TestDocumentsDate(test_utils.TmpFilesTestBase, cmptest.TestCase):
    TEST_DOCUMENTS: Any = ...
    def test_invalid_date(self) -> None: ...

class TestDocumentsConstraints(test_utils.TmpFilesTestBase, cmptest.TestCase):
    TEST_DOCUMENTS: Any = ...
    def test_find_documents__no_constraint(self) -> None: ...
    def test_find_documents__with_leaf_constraints(self) -> None: ...
    def test_find_documents__with_parent_constraints(self) -> None: ...
