from beancount.core import data as data
from beancount.ops import summarize as summarize
from typing import Any, Optional

def find_currencies_at_cost(entries: Any, date: Optional[Any] = ...): ...
def find_currencies_converted(entries: Any, date: Optional[Any] = ...): ...
def find_currencies_priced(entries: Any, date: Optional[Any] = ...): ...
def find_balance_currencies(entries: Any, date: Optional[Any] = ...): ...
