import unittest
from beancount import loader as loader
from beancount.ops import find_prices as find_prices
from typing import Any

class TestFromFile(unittest.TestCase):
    entries: Any = ...
    def setUp(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_find_currencies_converted(self) -> None: ...
    def test_find_currencies_at_cost(self) -> None: ...
    def test_find_currencies_priced(self) -> None: ...
    def test_find_balance_currencies(self) -> None: ...
