from beancount.core import account as account, account_types as account_types, amount as amount, data as data, flags as flags, getters as getters, position as position, prices as prices, realization as realization
from beancount.core.number import ZERO as ZERO
from beancount.ops import summarize as summarize
from beancount.parser import options as options
from beancount.utils import misc_utils as misc_utils
from collections import namedtuple
from typing import Any, Optional

Holding = namedtuple('Holding', 'account number currency cost_number cost_currency book_value market_value price_number price_date')

def get_final_holdings(entries: Any, included_account_types: Optional[Any] = ..., price_map: Optional[Any] = ..., date: Optional[Any] = ...): ...
def get_assets_holdings(entries: Any, options_map: Any, currency: Optional[Any] = ...): ...
def get_commodities_at_date(entries: Any, options_map: Any, date: Optional[Any] = ...): ...
def aggregate_holdings_by(holdings: Any, keyfun: Any): ...
def aggregate_holdings_list(holdings: Any): ...
def convert_to_currency(price_map: Any, target_currency: Any, holdings_list: Any): ...
def reduce_relative(holdings: Any): ...
def scale_holding(holding: Any, scale_factor: Any): ...
def holding_to_position(holding: Any): ...
def holding_to_posting(holding: Any): ...
