from beancount.core import data as data, inventory as inventory
from typing import Any, Optional

ONEDAY: Any

def get_commodity_lifetimes(entries: Any): ...
def compress_intervals_days(intervals: Any, num_days: Any): ...
def trim_intervals(intervals: Any, trim_start: Optional[Any] = ..., trim_end: Optional[Any] = ...): ...
def compress_lifetimes_days(lifetimes_map: Any, num_days: Any): ...

ONE_WEEK: Any

def required_weekly_prices(lifetimes_map: Any, date_last: Any): ...
def required_daily_prices(lifetimes_map: Any, date_last: Any, weekdays_only: bool = ...): ...
