from beancount import loader as loader
from beancount.ops import lifetimes as lifetimes
from beancount.utils import test_utils as test_utils
from typing import Any

class TestCommodityLifetimes(test_utils.TestCase):
    def test_lifetimes_different_currencies(self, entries: Any, errors: Any, _: Any) -> None: ...
    def test_lifetimes_closed_open(self, entries: Any, errors: Any, _: Any) -> None: ...
    def test_lifetimes_cross_accounts(self, entries: Any, errors: Any, _: Any) -> None: ...

class TestCompressLifetimes(test_utils.TestCase):
    def test_single_closed(self) -> None: ...
    def test_single_open(self) -> None: ...
    def test_multiple_no_compress(self) -> None: ...
    def test_multiple_compress(self) -> None: ...

class TestTrimLifetimes(test_utils.TestCase):
    def test_single_closed(self) -> None: ...
    def test_single_open(self) -> None: ...
    def test_multiple(self) -> None: ...

class TestLifetimeDateIterators(test_utils.TestCase):
    def test_iter_weeks(self) -> None: ...
    def test_iter_weekdays(self) -> None: ...
    def test_iter_days(self) -> None: ...
