from beancount.core.number import D as D
from beancount.prices import source as source
from typing import Any, Optional

class CoinbaseError(ValueError): ...

def fetch_quote(ticker: Any, time: Optional[Any] = ...): ...

class Source(source.Source):
    def get_latest_price(self, ticker: Any): ...
    def get_historical_price(self, ticker: Any, time: Any): ...
