import unittest
from beancount.core.number import D as D
from beancount.prices import source as source
from beancount.prices.sources import coinbase as coinbase
from typing import Any

def response(contents: Any, status_code: Any = ...): ...

class CoinbasePriceFetcher(unittest.TestCase):
    def test_error_network(self) -> None: ...
    def test_valid_response(self) -> None: ...
    def test_historical_price(self) -> None: ...
