from beancount.core.number import D as D
from beancount.prices import source as source
from collections import namedtuple
from typing import Any, Optional

class QuandlError(ValueError): ...

TickerSpec = namedtuple('TickerSpec', 'database dataset column')

def parse_ticker(ticker: Any): ...
def fetch_time_series(ticker: Any, time: Optional[Any] = ...): ...

class Source(source.Source):
    def get_latest_price(self, ticker: Any): ...
    def get_historical_price(self, ticker: Any, time: Any): ...
