import unittest
from beancount.core.number import D as D
from beancount.prices import source as source
from beancount.prices.sources import quandl as quandl
from beancount.utils import date_utils as date_utils
from typing import Any

def response(contents: Any, status_code: Any = ...): ...

class QuandlPriceFetcher(unittest.TestCase):
    def test_parse_ticker(self) -> None: ...
    def test_error_premium(self) -> None: ...
    def test_error_subscription(self) -> None: ...
    def test_error_network(self) -> None: ...
    def test_valid_response(self) -> None: ...
    def test_non_standard_columns(self) -> None: ...
