import unittest
from beancount.core.number import D as D
from beancount.prices.sources import tsp as tsp
from typing import Any

CURRENT_DATA: str
HISTORIC_DATA: str

class MockResponse:
    status_code: Any = ...
    def __init__(self, contents: Any, status_code: Any = ...) -> None: ...
    def iter_lines(self, decode_unicode: bool = ...): ...

class TSPFinancePriceFetcher(unittest.TestCase):
    def test_get_latest_price_L2050(self) -> None: ...
    def test_get_latest_price_SFund(self) -> None: ...
    def test_get_historical_price(self) -> None: ...
    def test_get_historical_price_L2060(self) -> None: ...
    def test_invalid_fund_latest(self) -> None: ...
    def test_invalid_fund_historical(self) -> None: ...
