import requests
from beancount.core.number import D as D
from beancount.prices import source as source
from typing import Any, Dict

class YahooError(ValueError): ...

def parse_response(response: requests.models.Response) -> Dict: ...
def parse_currency(result: Dict[str, Any]) -> str: ...

class Source(source.Source):
    def get_latest_price(self, ticker: Any): ...
    def get_historical_price(self, ticker: Any, time: Any): ...
