import unittest
from beancount.core.number import D as D
from beancount.prices.sources import yahoo as yahoo
from beancount.utils import date_utils as date_utils
from typing import Any

class MockResponse:
    status_code: Any = ...
    contents: Any = ...
    def __init__(self, contents: Any, status_code: Any = ...) -> None: ...
    def json(self, **kwargs: Any): ...

class YahooFinancePriceFetcher(unittest.TestCase):
    def test_get_latest_price(self) -> None: ...
    def test_get_historical_price(self) -> None: ...
    def test_parse_response_error_status_code(self) -> None: ...
    def test_parse_response_error_invalid_format(self) -> None: ...
    def test_parse_response_error_not_none(self) -> None: ...
