import unittest
from beancount.web import bottle_utils as bottle_utils
from typing import Any

class TestAttrMapper(unittest.TestCase):
    mapper: Any = ...
    def setUp(self) -> None: ...
    def test_AttrMapper(self) -> None: ...
    def test_AttrMapper_getattr(self) -> None: ...
    def test_AttrMapper_build(self) -> None: ...
