import unittest
from beancount.parser import version as version
from beancount.utils import test_utils as test_utils
from beancount.web import web as web
from typing import Any, Optional

class TestWeb(unittest.TestCase):
    ignore_regexp: Any = ...
    def check_page_okay(self, url: Any, response: Any, _: Any, __: Any, ___: Any) -> None: ...
    def scrape(self, filename: Any, extra_args: Optional[Any] = ...) -> None: ...
    def test_scrape_empty_file(self, filename: Any) -> None: ...
    def test_scrape_basic(self) -> None: ...
    def test_scrape_basic_view(self) -> None: ...
    def test_scrape_in_incognito(self) -> None: ...
    def test_scrape_starterkit(self) -> None: ...
