import unittest
from beancount import loader as loader
from beancount.parser import cmptest as cmptest
from beancount.plugins import book_conversions as book_conversions
from beancount.utils import test_utils as test_utils
from typing import Any

class TestBookConversions(cmptest.TestCase):
    def test_book_conversions_example(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_split_augmenting(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_split_reducing(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_zero_pnl(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_split_partial_failure(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_split_complete_failure(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_book_conversions_bad_configuration(self, entries: Any, errors: Any, __: Any) -> None: ...

class TestExtractTradesScript(unittest.TestCase):
    def test_extract_trades(self, filename: Any) -> None: ...
