from beancount import loader as loader
from beancount.core import account as account, amount as amount, data as data, inventory as inventory, position as position
from beancount.core.number import ZERO as ZERO
from beancount.parser import version as version
from beancount.utils import table as table
from collections import namedtuple
from typing import Any

__plugins__: Any
META: str

ConfigError = namedtuple('ConfigError', 'source message entry')

BookConversionError = namedtuple('BookConversionError', 'source message entry')

def is_matching(posting: Any, account: Any): ...
def augment_inventory(pending_lots: Any, posting: Any, entry: Any, eindex: Any): ...
def reduce_inventory(pending_lots: Any, posting: Any, eindex: Any): ...
def link_entries_with_metadata(entries: Any, all_matches: Any): ...
def book_price_conversions(entries: Any, assets_account: Any, income_account: Any): ...
def extract_trades(entries: Any): ...
def book_price_conversions_plugin(entries: Any, options_map: Any, config: Any): ...
def main() -> None: ...
