import unittest
from beancount import loader as loader
from beancount.plugins import check_commodity as check_commodity
from typing import Any

class TestCheckCommodity(unittest.TestCase):
    def test_get_commodity_map_ex(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_check_commodity_transaction(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_check_commodity_used_in_balance_only(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_check_commodity_okay(self, _: Any, errors: Any, __: Any) -> None: ...
