from beancount import loader as loader
from beancount.core import data as data
from beancount.parser import cmptest as cmptest
from beancount.plugins import currency_accounts as currency_accounts
from typing import Any

class TestCurrencyTradingAccounts(cmptest.TestCase):
    def test_selection(self, entries: Any, errors: Any, _: Any) -> None: ...
    def test_currency_conversion(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_custom_base_account(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_with_costs_ignored(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_with_costs_and_price(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_two_groups_already_balanced(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_residual_not_conversion(self, entries: Any, errors: Any, options_map: Any) -> None: ...
