from beancount import loader as loader
from beancount.parser import cmptest as cmptest
from typing import Any

class TestDivertExpenses(cmptest.TestCase):
    def test_divert(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_divert_some_postings(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_divert_non_expenses(self, entries: Any, errors: Any, __: Any) -> None: ...
