from beancount import loader as loader
from beancount.core import data as data
from beancount.core.number import D as D
from beancount.parser import cmptest as cmptest
from beancount.plugins import implicit_prices as implicit_prices
from typing import Any

class TestImplicitPrices(cmptest.TestCase):
    def test_add_implicit_prices__all_cases(self, entries: Any, _: Any, options_map: Any): ...
    def test_add_implicit_prices__other_account(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_add_implicit_prices__duplicates_on_same_transaction(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_add_implicit_prices__duplicates_on_different_transactions(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_add_implicit_prices__duplicates_overloaded(self, entries: Any, _: Any, options_map: Any) -> None: ...
