from beancount import loader as loader
from beancount.parser import cmptest as cmptest
from typing import Any

TmpFile: Any

class TestMergeMeta(cmptest.TestCase):
    def test_merge_meta__open(self) -> None: ...
    def test_merge_meta__close(self) -> None: ...
    def test_merge_meta__commodity(self) -> None: ...
    def test_merge_meta__multiple(self) -> None: ...
    def test_merge_meta__errors(self) -> None: ...
