from beancount import loader as loader
from beancount.core import compare as compare
from beancount.parser import cmptest as cmptest
from beancount.plugins import noduplicates as noduplicates
from typing import Any

class TestValidateDuplicates(cmptest.TestCase):
    def checkDuplicates(self, entries: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__open(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__close(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__pad(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__balance(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__transaction(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__note(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__event(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__document(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_validate_no_duplicates__price(self, entries: Any, errors: Any, options_map: Any) -> None: ...
