import unittest
from beancount import loader as loader
from typing import Any

class TestOneCommodity(unittest.TestCase):
    def test_one_commodity_transaction(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_one_commodity_balance(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_one_commodity_skip_declared(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_one_commodity_regexp_config(self, _: Any, errors: Any, __: Any) -> None: ...
    def test_one_commodity_skip_metadata(self, _: Any, errors: Any, __: Any) -> None: ...
