import unittest
from beancount import loader as loader
from beancount.ops import validation as validation
from beancount.parser import printer as printer
from beancount.plugins import sellgains as sellgains
from typing import Any

class TestSellGains(unittest.TestCase):
    def test_sellgains_success(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_sellgains_fail_balance(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_sellgains_fail_imbalance(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_sellgains_other_currency(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_sellgains_zero_price(self, entries: Any, errors: Any, options_map: Any) -> None: ...
