import unittest
from beancount import loader as loader
from beancount.parser import cmptest as cmptest
from beancount.plugins import split_expenses as split_expenses
from beancount.utils import test_utils as test_utils
from typing import Any

class TestSplitExpenses(cmptest.TestCase):
    def test_simple(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_unaffected(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_work_with_auto_accounts(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_with_one_member_only(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_other_directives_copied(self, entries: Any, errors: Any, __: Any) -> None: ...
    def test_tolerances__ignore_from_auto_postings(self, entries: Any, errors: Any, options_map: Any) -> None: ...

class TestSplitReports(unittest.TestCase):
    def run_split_reports(self, args: Any) -> None: ...
    def test_split_reports(self) -> None: ...
    def test_split_reports_with_currency(self) -> None: ...
