from beancount import loader as loader
from beancount.core import account as account, account_types as account_types, amount as amount, data as data, getters as getters, interpolate as interpolate
from beancount.parser import options as options, version as version
from beancount.query import query as query, query_render as query_render
from typing import Any, Optional

__plugins__: Any

def split_expenses(entries: Any, options_map: Any, config: Any): ...
def save_query(title: Any, participant: Any, entries: Any, options_map: Any, sql_query: Any, *format_args: Any, boxed: bool = ..., spaced: bool = ..., args: Optional[Any] = ...) -> None: ...
def get_participants(filename: Any, options_map: Any): ...
def main() -> None: ...
