from beancount.core import amount as amount, inventory as inventory, position as position
from typing import Any, Optional

def numberify_results(dtypes: Any, drows: Any, dformat: Optional[Any] = ...): ...

class IdentityConverter:
    name: Any = ...
    dtype: Any = ...
    index: Any = ...
    def __init__(self, name: Any, dtype: Any, index: Any) -> None: ...
    def __call__(self, drow: Any, _: Any): ...

class AmountConverter:
    dtype: Any = ...
    name: Any = ...
    index: Any = ...
    currency: Any = ...
    def __init__(self, name: Any, index: Any, currency: Any) -> None: ...
    def __call__(self, drow: Any, dformat: Any): ...

def convert_col_Amount(name: Any, drows: Any, index: Any): ...

class PositionConverter:
    dtype: Any = ...
    name: Any = ...
    index: Any = ...
    currency: Any = ...
    def __init__(self, name: Any, index: Any, currency: Any) -> None: ...
    def __call__(self, drow: Any, dformat: Any): ...

def convert_col_Position(name: Any, drows: Any, index: Any): ...

class InventoryConverter:
    dtype: Any = ...
    name: Any = ...
    index: Any = ...
    currency: Any = ...
    def __init__(self, name: Any, index: Any, currency: Any) -> None: ...
    def __call__(self, drow: Any, dformat: Any): ...

def convert_col_Inventory(name: Any, drows: Any, index: Any): ...

CONVERTING_TYPES: Any
