import unittest
from beancount.core import amount as amount, display_context as display_context, inventory as inventory, position as position
from beancount.core.amount import A as A
from beancount.core.number import D as D
from beancount.query import numberify as numberify
from typing import Any

class TestNumerifySimple(unittest.TestCase):
    input_amounts: Any = ...
    expected_types: Any = ...
    expected_rows: Any = ...
    def test_amount(self) -> None: ...
    def test_position(self) -> None: ...
    def test_inventory(self) -> None: ...

class TestNumerifyIdentity(unittest.TestCase):
    def test_identity(self) -> None: ...

class TestNumerifyInventory(unittest.TestCase):
    def test_inventory(self) -> None: ...

class TestNumerifyPrecision(unittest.TestCase):
    def test_precision(self) -> None: ...
