from beancount.core import convert as convert, display_context as display_context, realization as realization
from beancount.reports import base as base, tree_table as tree_table
from typing import Any

class BalancesReport(base.HTMLReport, metaclass=base.RealizationMeta):
    names: Any = ...
    default_format: str = ...
    @classmethod
    def add_args(cls, parser: Any) -> None: ...
    def render_real_text(self, real_root: Any, price_map: Any, price_date: Any, options_map: Any, file: Any): ...
    def render_real_htmldiv(self, real_root: Any, price_map: Any, price_date: Any, options_map: Any, file: Any) -> None: ...

class BalanceSheetReport(base.HTMLReport, metaclass=base.RealizationMeta):
    names: Any = ...
    default_format: str = ...
    def render_real_htmldiv(self, real_root: Any, price_map: Any, price_date: Any, options_map: Any, file: Any) -> None: ...

class IncomeStatementReport(base.HTMLReport, metaclass=base.RealizationMeta):
    names: Any = ...
    default_format: str = ...
    def render_real_htmldiv(self, real_root: Any, price_map: Any, price_date: Any, options_map: Any, file: Any) -> None: ...

__reports__: Any
