from beancount import loader as loader
from beancount.core import data as data
from beancount.parser import cmptest as cmptest
from beancount.reports import convert_reports as convert_reports, report as report
from beancount.scripts import example as example
from beancount.utils import test_utils as test_utils
from typing import Any

class TestLedgerUtilityFunctions(cmptest.TestCase):
    def test_quote_currency(self) -> None: ...

class TestLedgerUtilityFunctionsOnPostings(cmptest.TestCase):
    txns: Any = ...
    def setUp(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_postings_by_type(self) -> None: ...
    def test_split_currency_conversions(self) -> None: ...

def get_ledger_version(): ...

class TestLedgerConversion(test_utils.TestCase):
    def check_parses_ledger(self, ledger_filename: Any) -> None: ...
    def test_simple(self, filename: Any) -> None: ...
    def test_cost_and_foreign_currency(self, filename: Any) -> None: ...
    def test_tags_links(self, filename: Any) -> None: ...
    def test_example(self) -> None: ...

class TestHLedgerConversion(test_utils.TestCase):
    def test_tags_links(self, filename: Any) -> None: ...
    def test_example(self) -> None: ...
