import unittest
from beancount import loader as loader
from beancount.core import getters as getters
from beancount.core.number import D as D
from beancount.ops import holdings as holdings
from beancount.reports import export_reports as export_reports
from typing import Any

class TestHoldingsReports(unittest.TestCase):
    entries: Any = ...
    errors: Any = ...
    options_map: Any = ...
    def setUp(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_report_export_portfolio(self) -> None: ...

class TestCommodityClassifications(unittest.TestCase):
    def classify(fun: Any): ...
    def test_classify_explicit_symbol(self, action_holdings: Any) -> None: ...
    def test_classify_explicit_cash(self, action_holdings: Any) -> None: ...
    def test_classify_explicit_ignore(self, action_holdings: Any) -> None: ...
    def test_classify_ticker(self, action_holdings: Any) -> None: ...
    def test_classify_implicit(self, action_holdings: Any) -> None: ...
    def test_classify_money(self, action_holdings: Any) -> None: ...
    def test_get_money_instruments(self, entries: Any, errors: Any, options_map: Any) -> None: ...

EE: Any

class TestCommodityExport(unittest.TestCase):
    def export(self, entries: Any, options_map: Any, aggregate_by_commodity: bool = ...): ...
    def test_export_implicit_stock(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_implicit_mutfund(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_implicit_unspecified(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_implicit_absent(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_explicit_stock(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_cash_at_cost(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_cash_at_price(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_cash_ignored_no_money(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_ignored(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
    def test_export_aggregate(self, entries: Any, unused_errors: Any, options_map: Any) -> None: ...
