import unittest
from beancount import loader as loader
from beancount.core.number import Decimal as Decimal
from beancount.ops import holdings as holdings
from beancount.reports import holdings_reports as holdings_reports
from beancount.utils import table as table
from typing import Any

class TestHoldingsReports(unittest.TestCase):
    entries: Any = ...
    errors: Any = ...
    options_map: Any = ...
    def setUp(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_report_holdings(self) -> None: ...
    def test_report_networth(self) -> None: ...
    def test_load_from_csv(self) -> None: ...

class TestMultiCurrencyNetWorthCalculation(unittest.TestCase):
    entries: Any = ...
    errors: Any = ...
    options_map: Any = ...
    def setUp(self, entries: Any, errors: Any, options_map: Any) -> None: ...
    def test_calculate_net_worths(self) -> None: ...
