from beancount.core import display_context as display_context
from beancount.parser import printer as printer
from typing import Any

class HTMLFormatter:
    def __init__(self, dcontext: Any) -> None: ...
    def render_account(self, account_name: Any): ...
    def render_number(self, number: Any, currency: Any): ...
    def render_amount(self, amount: Any): ...
    def render_inventory(self, inv: Any): ...
    def render_context(self, entry: Any): ...
    def render_link(self, link: Any): ...
    def render_doc(self, filename: Any): ...
    def render_event_type(self, event: Any): ...
    def render_commodity(self, base_quote: Any): ...
    def render_source(self, meta: Any): ...
