import unittest
from beancount import loader as loader
from beancount.core import data as data, display_context as display_context, realization as realization
from beancount.reports import html_formatter as html_formatter, journal_html as journal_html
from typing import Any

class TestJournalRender(unittest.TestCase):
    entries: Any = ...
    real_account: Any = ...
    def setUp(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_iterate_html_postings(self) -> None: ...
    def test_html_entries_table_with_balance(self) -> None: ...
    def test_html_entries_table(self) -> None: ...
    def test_render_links(self) -> None: ...
