import unittest
from beancount import loader as loader
from beancount.core import data as data, position as position, realization as realization
from beancount.core.amount import A as A
from beancount.core.number import D as D
from beancount.reports import journal_text as journal_text
from typing import Any

class TestAmountColumnSizer(unittest.TestCase):
    def test_sizer(self) -> None: ...

class TestJournalRenderPosting(unittest.TestCase):
    number_format: str = ...
    def test_render_posting_no_cost(self) -> None: ...
    def test_render_posting_cost(self) -> None: ...
    def test_render_posting_price(self) -> None: ...
    def test_render_posting_cost_price(self) -> None: ...

class TestJournalTextRender(unittest.TestCase):
    entries: Any = ...
    real_account: Any = ...
    postings: Any = ...
    def setUp(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_get_entry_text_description(self) -> None: ...
    def test_combinations(self) -> None: ...
    def test_narrow(self) -> None: ...
