from beancount.core import convert as convert, data as data, realization as realization
from beancount.core.number import ZERO as ZERO
from typing import Any

TEXT_SHORT_NAME: Any

class AmountColumnSizer:
    prefix: Any = ...
    max_number: Any = ...
    max_currency_width: int = ...
    def __init__(self, prefix: Any) -> None: ...
    def update(self, number: Any, currency: Any) -> None: ...
    def get_number_width(self): ...
    def get_generic_format(self, precision: Any): ...
    def get_format(self, precision: Any): ...

COMPACT: Any
NORMAL: Any
VERBOSE: Any
FORMAT_TEXT: Any
FORMAT_CSV: Any

def text_entries_table(oss: Any, postings: Any, width: Any, at_cost: Any, render_balance: Any, precision: Any, verbosity: Any, output_format: Any) -> None: ...
def render_posting(posting: Any, number_format: Any): ...
def size_and_render_amounts(postings: Any, at_cost: Any, render_balance: Any): ...
def get_entry_text_description(entry: Any): ...
