from beancount.core import convert as convert, data as data, flags as flags, position as position, realization as realization
from collections import namedtuple
from typing import Any

FLAG_ROWTYPES: Any

Row = namedtuple('Row', 'entry leg_postings rowtype extra_class flag description links amount_str balance_str')

def iterate_html_postings(txn_postings: Any, formatter: Any) -> None: ...
def html_entries_table_with_balance(oss: Any, txn_postings: Any, formatter: Any, render_postings: bool = ...): ...
def html_entries_table(oss: Any, txn_postings: Any, formatter: Any, render_postings: bool = ...): ...
def render_links(links: Any): ...
