import argparse
from beancount import loader as loader
from beancount.ops import validation as validation
from beancount.parser import version as version
from beancount.reports import balance_reports as balance_reports, base as base, convert_reports as convert_reports, export_reports as export_reports, holdings_reports as holdings_reports, journal_reports as journal_reports, misc_reports as misc_reports, price_reports as price_reports
from beancount.utils import file_utils as file_utils, misc_utils as misc_utils, table as table
from typing import Any, Optional

def get_all_reports(): ...
def get_list_report_string(only_report: Optional[Any] = ...): ...

class ListReportsAction(argparse.Action):
    def __call__(self, parser: Any, namespace: Any, values: Any, option_string: Optional[Any] = ...) -> None: ...

class ListFormatsAction(argparse.Action):
    format_order: Any = ...
    format_order_last: int = ...
    def __call__(self, parser: Any, namespace: Any, values: Any, option_string: Optional[Any] = ...): ...

def main(argv: Optional[Any] = ...): ...
