import unittest
from beancount.reports import base as base, report as report
from beancount.utils import test_utils as test_utils
from typing import Any

class TestHelpReports(test_utils.TestCase):
    def test_get_list_report_string(self) -> None: ...
    def test_get_list_report_string__one_report(self) -> None: ...
    def test_get_list_report_string__invalid_report(self) -> None: ...

class TestReportFunctions(unittest.TestCase):
    def test_get_all_report(self) -> None: ...

class TestScriptQuery(test_utils.TestCase):
    def test_list_accounts_empty(self, filename: Any) -> None: ...

class TestScriptPositions(test_utils.TestCase):
    def test_success(self, filename: Any) -> None: ...
    def test_print_trial(self, filename: Any) -> None: ...
    def test_print_trial_empty(self, filename: Any) -> None: ...
    def test_all_prices(self, filename: Any) -> None: ...
    def test_list_accounts(self, filename: Any) -> None: ...
    def test_list_accounts_empty(self, filename: Any) -> None: ...
    def test_export_portfolio_on_example(self) -> None: ...
