import unittest
from beancount.tools import sheets_upload as sheets_upload
from typing import Any

oauth2client: Any

class TestPopAlist(unittest.TestCase):
    def test_pop_alist__empty(self) -> None: ...
    def test_pop_alist__not_found(self) -> None: ...
    def test_pop_alist__found(self) -> None: ...
    def test_pop_alist__not_unique(self) -> None: ...

class TestSheetsUtils(unittest.TestCase):
    def test_get_alpha_column(self) -> None: ...
    def test_sheet_range(self) -> None: ...
