from typing import Any, List, Optional

EMPTY_SHEET_TITLE: str

def get_credentials(scopes: List[str], secrets_filename: Optional[str]=..., storage_filename: Optional[str]=...) -> Any: ...
def pop_alist(items: Any, key: Any, default: Optional[Any] = ...): ...
def get_alpha_column(column: Any): ...
def sheet_range(nrows: Any, ncols: Any, title: Optional[Any] = ...): ...
def create_doc(service: Any): ...

class Doc:
    service: Any = ...
    docid: Any = ...
    min_rows: Any = ...
    def __init__(self, service: Any, docid: Any, min_rows: Any) -> None: ...
    def delete_empty_sheets(self) -> None: ...
    def get_sheets(self): ...
    def add_sheet(self, title: Any): ...
    def get_sheet_size(self, title: Any): ...
    def clear_sheet(self, title: Any, nrowcols: Optional[Any] = ...) -> None: ...
    def resize_sheet(self, sheet_id: Any, title: Any, nrows: Any, ncols: Any) -> None: ...
    def auto_resize_sheet(self, sheet_id: Any) -> None: ...
    def update_sheet(self, sheet_id: Any, title: Any, filename: Any) -> None: ...
    def set_title(self, doctitle: Any) -> None: ...

def match_names_and_upload_sheets(service: Any, docid: Any, new_sheets: Any, min_rows: Any) -> None: ...
def main() -> None: ...
