from typing import Any

DEFAULT_PATTERN: str
DEFAULT_DELIMITER: str
DEFAULT_SPLITTER: str
LOOSE_PATTERN: str
LOOSE_SPLITTER: str
FILENAME_PATTERN: str
FILENAME_SPLITTER: str

def find_column(lines: Any, pattern: Any, delimiter: Any): ...

class Node(list):
    name: Any = ...
    nos: Any = ...
    def __init__(self, name: Any) -> None: ...

def dump_tree(node: Any, file: Any = ..., prefix: str = ...) -> None: ...
def create_tree(column_matches: Any, regexp_split: Any): ...

PREFIX_CHILD_1: str
PREFIX_CHILD_C: str
PREFIX_LEAF_1: str
PREFIX_LEAF_C: str

def render_tree(root: Any): ...
def enum_tree_by_input_line_num(tree_lines: Any) -> None: ...
def main() -> None: ...
