from beancount import loader as loader
from beancount.core import getters as getters
from beancount.projects import will as will
from beancount.utils import test_utils as test_utils
from typing import Any

def setUp(self) -> None: ...

class TestWillFunctions(test_utils.TestCase):
    maxDiff: Any = ...
    def test_group_accounts(self, entries: Any, _: Any, __: Any) -> None: ...
    def test_find_institutions(self, entries: Any, _: Any, options_map: Any) -> None: ...
    def test_get_first_meta(self, entries: Any, _: Any, options_map: Any) -> None: ...

class TestWillReport(test_utils.TestCase):
    def test_create_report(self, entries: Any, _: Any, options_map: Any) -> None: ...
