from beancount.ingest import importer as importer
from typing import Any

def validate_config(config: Any, schema: Any, importer: Any): ...

class ConfigMixin(importer.ImporterProtocol):
    REQUIRED_CONFIG: Any = ...
    config: Any = ...
    def __init__(self, **kwds: Any) -> None: ...
