from beancount.core import account as account
from beancount.ingest import importer as importer
from typing import Any

class FilingMixin(importer.ImporterProtocol):
    filing_account: Any = ...
    prefix: Any = ...
    def __init__(self, **kwds: Any) -> None: ...
    def name(self): ...
    def file_account(self, file: Any): ...
    def file_name(self, file: Any): ...
