from beancount.ingest import cache as cache, importer as importer
from typing import Any

def identify(remap: Any, converter: Any, file: Any): ...

class IdentifyMixin(importer.ImporterProtocol):
    remap: Any = ...
    converter: Any = ...
    def __init__(self, **kwds: Any) -> None: ...
    def identify(self, file: Any): ...
